CREATE TABLE [dbo].[Job]
(
[Id] [int] NOT NULL IDENTITY(1, 1),
[Name] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Enabled] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[EmailProfileId] [int] NOT NULL,
[AlertEmailProfileId] [int] NULL,
[ChecksDatabaseName] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[LastRun] [datetime] NULL,
[NextRun] [datetime] NULL,
[TryUntil] [datetime] NULL,
[IgnoreChecksNextRun] [bit] NOT NULL CONSTRAINT [DF_Job_IgnoreChecksNextRun] DEFAULT ((0)),
[creation_date] [datetime] NOT NULL CONSTRAINT [DF_Job_creation_date] DEFAULT (getdate()),
[last_updated_date] [datetime] NOT NULL CONSTRAINT [DF_Job_last_updated_date] DEFAULT (getdate()),
[ReportDatabaseName] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SpecialParameterId] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SuppressCheckFailureAlert] [int] NULL,
[SuppressSendIfNoData] [bit] NULL,
[NextRunMailComments] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SuppressMailSendNextRun] [bit] NULL,
[CategoryId] [int] NULL,
[deleted] [tinyint] NOT NULL CONSTRAINT [DF__Job__deleted__4850AF91] DEFAULT ((0))
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE TRIGGER [dbo].[trg_Job_updated]
ON [dbo].[Job]
FOR UPDATE
AS
--start_autogenerated_trigger_text  - do not edit comments or code!
IF (suser_name() = 'svc_sync_user') OR (suser_name() = 'svc_agent_user')  RETURN
--end_autogenerated_trigger_text

BEGIN

 SET NOCOUNT ON 

 UPDATE dbo.Job SET dbo.Job.last_updated_date = GETDATE()
 FROM inserted
 WHERE inserted.Id = dbo.Job.Id

END
GO
ALTER TABLE [dbo].[Job] ADD CONSTRAINT [PK_Job] PRIMARY KEY CLUSTERED  ([Id]) ON [PRIMARY]
GO
