CREATE TABLE [dbo].[JobSpreadsheetDetail]
(
[JobId] [int] NOT NULL,
[SpreadsheetId] [int] NOT NULL,
[TargetFilename] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[creation_date] [datetime] NOT NULL CONSTRAINT [DF_JobSpreadsheetDetail_creation_date] DEFAULT (getdate()),
[last_updated_date] [datetime] NOT NULL CONSTRAINT [DF_JobSpreadsheetDetail_last_updated_date] DEFAULT (getdate())
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE TRIGGER [dbo].[trg_JobSpreadsheetDetail_updated]
ON [dbo].[JobSpreadsheetDetail]
FOR UPDATE
AS
--start_autogenerated_trigger_text  - do not edit comments or code!
IF (suser_name() = 'svc_sync_user') OR (suser_name() = 'svc_agent_user')  RETURN
--end_autogenerated_trigger_text

BEGIN

 SET NOCOUNT ON 

 UPDATE dbo.JobSpreadsheetDetail SET dbo.JobSpreadsheetDetail.last_updated_date = GETDATE()
 FROM inserted
 WHERE inserted.JobId = dbo.JobSpreadsheetDetail.JobId

END
GO
ALTER TABLE [dbo].[JobSpreadsheetDetail] ADD CONSTRAINT [PK_JobSpreadsheetDetail] PRIMARY KEY CLUSTERED  ([JobId], [SpreadsheetId]) ON [PRIMARY]
GO
