CREATE TABLE [dbo].[ArgumentValues]
(
[Id] [int] NOT NULL,
[Description] [varchar] (512) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[creation_date] [datetime] NOT NULL CONSTRAINT [DF_ArgumentValues_creation_date] DEFAULT (getdate()),
[last_updated_date] [datetime] NOT NULL CONSTRAINT [DF_ArgumentValues_last_updated_date] DEFAULT (getdate())
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE TRIGGER [dbo].[trg_ArgumentValues_updated]
ON [dbo].[ArgumentValues]
FOR UPDATE
AS
--start_autogenerated_trigger_text  - do not edit comments or code!
IF (suser_name() = 'svc_sync_user') OR (suser_name() = 'svc_agent_user')  RETURN
--end_autogenerated_trigger_text

BEGIN

 SET NOCOUNT ON 

 UPDATE dbo.ArgumentValues SET dbo.ArgumentValues.last_updated_date = GETDATE()
 FROM inserted
 WHERE inserted.Id = dbo.ArgumentValues.Id

END
GO
ALTER TABLE [dbo].[ArgumentValues] ADD CONSTRAINT [PK_ArgumentValues] PRIMARY KEY CLUSTERED  ([Id]) ON [PRIMARY]
GO
