CREATE TABLE [dbo].[DataRefreshTypes]
(
[RefreshType] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Command] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[last_updated_date] [datetime] NOT NULL CONSTRAINT [DF_DataRefreshTypes_last_updated_date] DEFAULT (getdate()),
[creation_date] [datetime] NOT NULL CONSTRAINT [DF_DataRefreshTypes_creation_date] DEFAULT (getdate())
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO



create TRIGGER [dbo].[trg_DataRefreshTypes_updated]
ON [dbo].[DataRefreshTypes]
FOR UPDATE
AS
--start_autogenerated_trigger_text  - do not edit comments or code!
IF (suser_name() = 'svc_sync_user') OR (suser_name() = 'svc_agent_user')  RETURN
--end_autogenerated_trigger_text

BEGIN

 SET NOCOUNT ON 

 UPDATE dbo.DataRefreshTypes SET dbo.DataRefreshTypes.last_updated_date = GETDATE()
 FROM inserted
 WHERE inserted.RefreshType = dbo.DataRefreshTypes.RefreshType

END
GO
ALTER TABLE [dbo].[DataRefreshTypes] ADD CONSTRAINT [PK_DataRefreshTypes] PRIMARY KEY CLUSTERED  ([RefreshType]) ON [PRIMARY]
GO
