CREATE TABLE [dbo].[JobReportDetail]
(
[JobId] [int] NOT NULL,
[ReportId] [int] NOT NULL,
[SaveAs] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TargetFilename] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[creation_date] [datetime] NOT NULL CONSTRAINT [DF_JobReportDetail_creation_date] DEFAULT (getdate()),
[last_updated_date] [datetime] NOT NULL CONSTRAINT [DF_JobReportDetail_last_updated_date] DEFAULT (getdate())
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE TRIGGER [dbo].[trg_JobReportDetail_updated]
ON [dbo].[JobReportDetail]
FOR UPDATE
AS
--start_autogenerated_trigger_text  - do not edit comments or code!
IF (suser_name() = 'svc_sync_user') OR (suser_name() = 'svc_agent_user')  RETURN
--end_autogenerated_trigger_text

BEGIN

 SET NOCOUNT ON 

 UPDATE dbo.JobReportDetail SET dbo.JobReportDetail.last_updated_date = GETDATE()
 FROM inserted
 WHERE inserted.JobId = dbo.JobReportDetail.JobId

END
GO
ALTER TABLE [dbo].[JobReportDetail] ADD CONSTRAINT [PK_JobReportDetail] PRIMARY KEY CLUSTERED  ([JobId], [ReportId]) ON [PRIMARY]
GO
