CREATE TABLE [dbo].[Checks]
(
[Id] [int] NOT NULL,
[Description] [varchar] (512) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[creation_date] [datetime] NOT NULL CONSTRAINT [DF_Checks_creation_date] DEFAULT (getdate()),
[last_updated_date] [datetime] NOT NULL CONSTRAINT [DF_Checks_last_updated_date] DEFAULT (getdate())
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE TRIGGER [dbo].[trg_Checks_updated]
ON [dbo].[Checks]
FOR UPDATE
AS
--start_autogenerated_trigger_text  - do not edit comments or code!
IF (suser_name() = 'svc_sync_user') OR (suser_name() = 'svc_agent_user')  RETURN
--end_autogenerated_trigger_text

BEGIN

 SET NOCOUNT ON 

 UPDATE dbo.Checks SET dbo.Checks.last_updated_date = GETDATE()
 FROM inserted
 WHERE inserted.Id = dbo.Checks.Id

END
GO
ALTER TABLE [dbo].[Checks] ADD CONSTRAINT [PK_Checks] PRIMARY KEY CLUSTERED  ([Id]) ON [PRIMARY]
GO
