CREATE TABLE [dbo].[SpecialParameters]
(
[ID] [int] NOT NULL IDENTITY(1000, 1),
[IDString] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IDParam] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IDValue] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[creation_date] [datetime] NOT NULL CONSTRAINT [DF_SpecialParameters_creation_date] DEFAULT (getdate()),
[last_updated_date] [datetime] NOT NULL CONSTRAINT [DF_SpecialParameters_last_updated_date] DEFAULT (getdate()),
[IDValueDateTime] [datetime] NULL
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[trg_SpecialParameters_updated]
ON [dbo].[SpecialParameters]
FOR UPDATE
AS
--start_autogenerated_trigger_text  - do not edit comments or code!
IF (suser_name() = 'svc_sync_user') OR (suser_name() = 'svc_agent_user')  RETURN
--end_autogenerated_trigger_text

BEGIN

 SET NOCOUNT ON 

 UPDATE dbo.SpecialParameters SET dbo.SpecialParameters.last_updated_date = GETDATE()
 FROM inserted
 WHERE inserted.Id = dbo.SpecialParameters.Id

END
GO
ALTER TABLE [dbo].[SpecialParameters] ADD CONSTRAINT [PK_SpecialParameters] PRIMARY KEY CLUSTERED  ([ID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [ix_SpecialParameters] ON [dbo].[SpecialParameters] ([IDString], [IDParam]) INCLUDE ([IDValue]) ON [PRIMARY]
GO
