CREATE TABLE [dbo].[SMTPProfile]
(
[Id] [int] NOT NULL IDENTITY(1, 1),
[Description] [varchar] (512) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Port] [int] NOT NULL,
[Server] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Username] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Password] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[UseSSL] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[creation_date] [datetime] NOT NULL CONSTRAINT [DF_SMTPProfile_creation_date] DEFAULT (getdate()),
[last_updated_date] [datetime] NOT NULL CONSTRAINT [DF_SMTPProfile_last_updated_date] DEFAULT (getdate())
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE TRIGGER [dbo].[trg_SMTPProfile_updated]
ON [dbo].[SMTPProfile]
FOR UPDATE
AS
--start_autogenerated_trigger_text  - do not edit comments or code!
IF (suser_name() = 'svc_sync_user') OR (suser_name() = 'svc_agent_user')  RETURN
--end_autogenerated_trigger_text

BEGIN

 SET NOCOUNT ON 

 UPDATE dbo.SMTPProfile SET dbo.SMTPProfile.last_updated_date = GETDATE()
 FROM inserted
 WHERE inserted.Id = dbo.SMTPProfile.Id

END
GO
ALTER TABLE [dbo].[SMTPProfile] ADD CONSTRAINT [PK_SMTPProfile] PRIMARY KEY CLUSTERED  ([Id]) ON [PRIMARY]
GO
