CREATE TABLE [dbo].[EmailProfile]
(
[Id] [int] NOT NULL IDENTITY(1, 1),
[Description] [varchar] (512) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Subject] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Message] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MailTo] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FromSMTPProfileId] [int] NOT NULL,
[Cc] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Bcc] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[creation_date] [datetime] NOT NULL CONSTRAINT [DF_EmailProfile_creation_date] DEFAULT (getdate()),
[last_updated_date] [datetime] NOT NULL CONSTRAINT [DF_EmailProfile_last_updated_date] DEFAULT (getdate())
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE TRIGGER [dbo].[trg_EmailProfile_updated]
ON [dbo].[EmailProfile]
FOR UPDATE
AS
--start_autogenerated_trigger_text  - do not edit comments or code!
IF (suser_name() = 'svc_sync_user') OR (suser_name() = 'svc_agent_user')  RETURN
--end_autogenerated_trigger_text

BEGIN

 SET NOCOUNT ON 

 UPDATE dbo.EmailProfile SET dbo.EmailProfile.last_updated_date = GETDATE()
 FROM inserted
 WHERE inserted.Id = dbo.EmailProfile.Id

END
GO
ALTER TABLE [dbo].[EmailProfile] ADD CONSTRAINT [PK_EmailProfile] PRIMARY KEY CLUSTERED  ([Id]) ON [PRIMARY]
GO
