CREATE TABLE [dbo].[JobCategory]
(
[CategoryId] [int] NOT NULL,
[CatDesc] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[last_updated_date] [datetime] NOT NULL CONSTRAINT [DF_JobCategory_last_updated_date] DEFAULT (getdate()),
[creation_date] [datetime] NOT NULL CONSTRAINT [DF_JobCategory_creation_date] DEFAULT (getdate())
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


create TRIGGER [dbo].[trg_JobCategory_updated]
ON [dbo].[JobCategory]
FOR UPDATE
AS
--start_autogenerated_trigger_text  - do not edit comments or code!
IF (suser_name() = 'svc_sync_user') OR (suser_name() = 'svc_agent_user')  RETURN
--end_autogenerated_trigger_text

BEGIN

 SET NOCOUNT ON 

 UPDATE dbo.JobCategory SET dbo.JobCategory.last_updated_date = GETDATE()
 FROM inserted
 WHERE inserted.CategoryId = dbo.JobCategory.CategoryId

END
GO
ALTER TABLE [dbo].[JobCategory] ADD CONSTRAINT [PK_JobCategory] PRIMARY KEY CLUSTERED  ([CategoryId]) ON [PRIMARY]
GO
