CREATE TABLE [dbo].[JobCustomReportDetail]
(
[JobId] [int] NOT NULL,
[CustomReportId] [int] NOT NULL,
[TargetFilename] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[creation_date] [datetime] NOT NULL CONSTRAINT [DF_JobCustomReportDetail_creation_date] DEFAULT (getdate()),
[last_updated_date] [datetime] NOT NULL CONSTRAINT [DF_JobCustomReportDetail_last_updated_date] DEFAULT (getdate())
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE TRIGGER [dbo].[trg_JobCustomReportDetail_updated]
ON [dbo].[JobCustomReportDetail]
FOR UPDATE
AS
--start_autogenerated_trigger_text  - do not edit comments or code!
IF (suser_name() = 'svc_sync_user') OR (suser_name() = 'svc_agent_user')  RETURN
--end_autogenerated_trigger_text

BEGIN

 SET NOCOUNT ON 

 UPDATE dbo.JobCustomReportDetail SET dbo.JobCustomReportDetail.last_updated_date = GETDATE()
 FROM inserted
 WHERE inserted.JobId = dbo.JobCustomReportDetail.JobId

END
GO
ALTER TABLE [dbo].[JobCustomReportDetail] ADD CONSTRAINT [PK_JobCustomReportDetail] PRIMARY KEY CLUSTERED  ([JobId], [CustomReportId]) ON [PRIMARY]
GO
